### ISSUE TITLE
코드 리뷰

### ISSUE THREAD

**Issue by heunyam** [GRAM-DSM/GRAMO-Backend-Flask#1]
`.gitignore` 파일 추가해서 __pycache__ 없애기
[gitignore 파일 생성기](http://gitignore.io/)
[깃허브에 잘못올라간 파일 삭제하기](https://velog.io/@heunyam/%EA%B9%83%ED%97%88%EB%B8%8C%EC%97%90-%EC%9E%98%EB%AA%BB-%EC%98%AC%EB%9D%BC%EA%B0%84-%ED%8C%8C%EC%9D%BC-%ED%9E%88%EC%8A%A4%ED%86%A0%EB%A6%AC-%EC%82%AD%EC%A0%9C%ED%95%98%EA%B8%B0)

**Comment by heunyam** [comment]
https://github.com/GRAM-DSM/GRAMO-Backend-Flask/blob/07419e1d96/server/app.py

Base.metadata.create_all() 은 코드를 봤을 때 작동하지 않음 -> 왜일까 생각해보기
JWTManager(app) 코드도 create_app() 에서 하는게 좋을 듯

**Comment by heunyam** [comment]
https://github.com/GRAM-DSM/GRAMO-Backend-Flask/blob/07419e1d96/server/__init__.py

flask_mysqldb 어디에 쓰고 있어?

**Comment by heunyam** [comment]
https://github.com/GRAM-DSM/GRAMO-Backend-Flask/blob/07419e1d96/server/model/notice.py

id Column에 autoincrement=True 옵션 없는 거 같음

**Comment by heunyam** [comment]
```python
if del_notice:        
	if del_notice.user_email == user_email:            				 
   		session.delete(del_notice)
        session.commit()
        return {
        	"message": "success"
		}, 204        
	else:            
		abort(403, 'could not delete notice created by others')    
else:        
	abort(404, 'could not find notice matching this id')
```
guard clause pattern 을 쓰자

```python
if not del_notice:
	abort(404, 'could not find notice matching this id')
if not del_notice.user_email == user_email: 
	abort(403, 'could not delete notice created by others')

session.delete(del_notice)
session.commit()
return {
   "message": "success"
}, 204
```
이렇게 하면 깔끔

나머지 if / else 쓰는 코드도 리팩토링 해보삼

**Comment by JoMingyu** [comment]
`werkzeug.exceptions` 이용해서 `abort` 말고 `raise` 쓰는 것 추천

as-is
```python
abort(404, 'something')
```

to-be
```python
raise NotFound('something')
```

IDE 도움을 더 많이 받을 수 있음(`raise`문은 block을 종료하므로).
